stages:
  - build
  - test
  - deploy

cache:
  paths:
  - projects/s4w_public_template

build:
  stage: build
  tags:
    - public
  script:
    - echo 'building app'
    - echo 'testing2'
    - npm install
    - echo 'installed >'


run_test:
  stage: test
  tags:
    - public
  script:
    - echo 'running test'

deploy_production:
  stage: deploy
  tags:
    - public
  script:
    - echo 'public app deployed'
