stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - public
  script:
    - echo 'hello from gitlab-runner'
    - echo 'testing1'
    - sudo screen -r


run_test:
  stage: test
  tags:
    - public
  script:
    - echo 'running test'

deploy_production:
  stage: deploy
  tags:
    - public
  script:
    - echo 'public app deployed'
