stages:
  - build
  - test
  - deploy

cache:
  paths:
  - projects/s4w_public_template

build:
  stage: build
  tags:
    - public
  script:
    - ls
    - echo 'hello from gitlab-runner'
    - echo 'testing2'
    - whoami
    - screen -r


run_test:
  stage: test
  tags:
    - public
  script:
    - echo 'running test'

deploy_production:
  stage: deploy
  tags:
    - public
  script:
    - echo 'public app deployed'
